---
title: "Homework 2"
subtitle:  "Joint, Marginal and Conditional"
graphics: yes
output: pdf_document
header-includes:
    - \usepackage{amsmath}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

* * * 
### Instructions

Please answer the following questions in the order in which they are posed. Add a few empty lines below each and write your answers there. Focus on answering in complete sentences. You will also need scratch paper/pen to work out the answers before typing it.

For help with formatting documents in RMarkdown, please consult [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/). Another option is to search using Google. 

* * *

### Exercises 

1. (Joint PMF) An urn contains four red chips, three white chips,
and two blue chips. A random sample of size 3 is drawn
without replacement. Let $X$ denote the number of white
chips in the sample and $Y$ the number of blue chips. Write
a formula for the joint PMF of $X$ and $Y$. Be sure to explain the components of your formula and why it makes sense. 

   \emph{Hint: You will first want to make a table on scratch paper to understand the possible values for $x$ and $y$ and their corresponding probabilities. Then the formula for the PMF will be evident}


2. (Multinomial) Let $U_1,U_2, . . . ,U_{1029}$ be independent
uniformly distributed random variables. Let $X_1$ equal the number of $U_i$ less than
.331, $X_2$ equal the number between .331 and .820, and $X_3$ equal the number greater than .820.


   a. Calculate, using, R the probability of observing $X_1 = 354, X_2 = 492, X_3 = 183$. Be sure to show your code. State the joint distribution before launching into calculations. 
   
   b. Calculate, using R as a calculator, the expected values and standard deviation of $X_2$? Be sure to show your code. State the marginal distribution before launching into calculations.
   
3. (Marginal PMF) Let $X$ and $Y$ be discrete random variables with joint PMF 
$$f(x, y) = \left(\frac{\lambda}{2} \right)^{y} \frac{e^{-\lambda}}{x! \:(y-x)!}$$

   where $x$ and $y$ are (non-negative) integers and $0 \leq x \leq y$. That is, $x, y = 0, 1, 2, 3, \dots$ but with the constraint $0 \leq x \leq y$.

   Determine $f_2(y)$, the marginal distribution of $Y$. Is this a familiar distribution? Show the steps.
   
      \emph{Hint: you will need to use the Binomial theorem with a = 1 and b = 1 to perform the summation over $x$. }  

4. (Hierarchical model) Suppose a player is equally likely to have 4, 5 or 6 at-bats (opportunities to bat) in a baseball game. If $X$ is the number of opportunities to bat, then we are assuming that
$$f_1(x) = P(X = x) = \frac{1}{3}, \ \ \ x = 4, 5,6.$$
Suppose $Y$, the number of hits, is a Binomial random variable with size $X = x$ and probability of success $\pi=0.3$. That is 
$$f(y|x) = P(Y = y | X = x) = Binom(x, 0.3).$$
 
a. Fill in the numbers for the joint PMF, $f(x,y) = P(X = x, Y = y)$ in the cells indicated by (i) -- (v). Also fill in the number for the marginal PMF $f_2(y)$ in the cell indicated by (vi). Show work below the table so we know you are not just guessing.

\begin{table}[h]
\centering
\begin{tabular}{||c|c|c|c|c|c|c|c||} \hline
& \multicolumn{7}{c||}{$y$} \\ \hline
$x$ & 0 & 1 & 2 & 3 & 4 & 5 & 6  \\ \hline
4 & \hspace*{0.2in} & \hspace*{0.2in} & (i) & \hspace*{0.2in}& (ii) & (iii) & \\ \hline \hline
5 & & & (iv) & & & &  \\ \hline  \hline
6 & & & (v) & & & &   \\ \hline \hline
$f_2(y)$ & & & (vi) & & & & \\ \hline
\end{tabular}
\end{table}



b. Write the conditional distribution of $X$ given $Y=2$. That is $$f(x|y=2) = P(X = x | Y = 2).$$ Again, be sure to state any formulas you are plugging into so we know you are not guessing.
