---
title: "Homework 4"
subtitle:  "Combining Random Variables"
graphics: yes
output: pdf_document
header-includes:
    - \usepackage{amsmath,diagbox}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

* * * 
### Instructions

Please answer the following questions in the order in which they are posed. Add a few empty lines below each and write your answers there. \textbf{Focus on answering in complete sentences and show work whether we ask for it or not}. You will also need scratch paper/pen to work out the answers before typing it.

For help with formatting documents in RMarkdown, please consult [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/). Another option is to search using Google. 

* * *

### Exercises 

1. (Floods) Suppose that many years of observation have confirmed that the annual maximum
flood tide $X$ (in feet) for a certain river can be modeled by the PDF
$$f(x) = \frac{1}{20} \ \ \ \ 20 < x < 40$$
The Army Corps of Engineers is planning to build a levee along a certain portion of the river and they want to make it high enough so there is only a 20% chance that the worst flood in the next thirty years will overflow the embankment. How high should the levee be?

   Be sure to define random variables, show your derivations and clearly highlight important intermediate steps so we don't miss them.

   
2. (Two Poissons) Suppose $X_1, X_2, \dots, X_n \overset{i.i.d.}{\sim} Pois(\lambda)$. 
That is, the PMF of each $X$ is
$$f(x) = e^{-\lambda} \frac{\lambda^{x}}{x!}, \ \ \ x=0,1,2,\dots$$
Show, using mathematical induction that
$$S = X_1 + X_2 + \dots + X_{n} \sim Pois(n \lambda).$$

   Hint: Look at Example 16.1 and Theorem 16.2 for the proof for the Binomial distribution. 


3. (Three normals) The	random	variables	$X_1$,	$X_2$ and	$X_3$ are	independent	$Norm(\mu, 1)$.	Let $\bar{X}$ be	the	
(arithmetic)	average	of	the	three	random	variables.	That is:
$$\bar{X} = \frac{1}{3} \left(X_1 + X_2 + X_3 \right).$$

   What is the probability	that $Y = (X_1	- \bar{X}) >	1.6$?

   Be sure to write the distribution of $Y$ clearly, cite any results you use, then show the calculation including any code you write to do your calculations. 

   *Hint* Write $Y$ as a linear combination of the $X$'s. No further hints on this. You are expected to figure it out.
   
4. (Call center) Let the Poisson random variable $X$ be
the number of calls for technical assistance received by a
computer company during the firm’s nine normal workday hours. Suppose the average number of calls per hour
is 7.0 and that each call costs the company \$50. Let $V$ be a
Poisson random variable representing the number of calls
for technical assistance received during a day’s remaining fifteen hours. Suppose the average number of calls per
hour is 4.0 for that time period and that each such call costs
the company \$60. 

   a. Let the random variable $C$ denote the cost associated with the calls received during a 24 hour day. Write $C$ as a function of $X$ and $Y$. 
   
   \emph{No hints on how to do this. You are expected to figure it out.}
   
   b. Find the expected cost and the variance of the random variable $C$. Be sure to state any assumptions you make in order to do your calculation. And show your work.