---
title: "Problem Section 7"
subtitle:  "Significance Tests"
graphics: yes
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

* * * 
### Instructions

Please answer the following questions in the order in which they are posed. Add a few empty lines below each and write your answers there. Focus on answering in complete sentences. You will also need scratch paper/pen to work out the answers before typing it.

For help with formatting documents in RMarkdown, please consult [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/). Another option is to search using Google. 

* * *

### Exercises 

1. A children's game uses a six sided die with a picture of a ghost named Hugo on one side and numbers on the other sides. If the die is fair, the ghost should be rolled 1/6 of the time. You test the die by rolling it $n=10$ times and and the ghost is rolled $x=3$ times.  Calculate the p-value for an exact binomial test of the hypothesis
$$H_0: \pi = \frac{1}{6} \ \ \ H_1: \pi \neq \frac{1}{6}$$

2. As input for a new inflation model, economists
predicted that the average cost of a hypothetical "food
basket" in western WA in July would be \$145.75. The
standard deviation ($\sigma_0$) of basket prices was assumed to be
$9.50, a figure that has held fairly constant over the years.
To check their prediction, a sample of twenty-five baskets
representing different parts of the region were checked in
late July, and the average cost was \$149.75. 

a. Let $\mu_0$ denote the true mean price of the food basket in July in Western WA. Write the null and alternative hypothesis.

b. Suppose the test will be based on $\bar{X}$ the sample mean. What is its null sampling distribution?  (You may assume the CLT applies)

c. Calculate the P-value associated with $\bar{x} = \$149.75$. 



3. An experimenter takes a sample of size 4 - $X_1, X_2, X_3,X_4$ - from
the Poisson probability model, 
$$f(x) = e^{-\lambda_0} \frac{\lambda_0^{x}}{x!} \ \ \ x=0,1,2, \dots$$
 and wishes to test
$H0: \lambda_0 = 6$ versus $H_1: \lambda_0 < 6$ 
at level $\alpha = 0.1$ The test will be based on the statistic $S = X_1+X_2+X_3+X_4$. 

   a. Find the Type 1 error rate for the test.
   
   b. Calculate the Type 2 error rate when $\lambda_0 = 4$. 
   
   
4. An urn contains ten marbles: an unknown number of them are white, the rest red. We wish to test:
$$H_0: \mbox{exactly half are white}$$
versus 
$$H_1: \mbox{more than half are white}$$
We will draw randomly, without replacement, three marbles and reject $H_0$ if two or more are white.

   a. Find the Type I error rate of this test. (Hint: the number of white marbles among the three drawn is a Hypergeometric random variable)
   
   b. Find the Type II error rate in two situations.
   
      - 60\% of the marbles in the urn are white
      
      - 70\% of the marbles in the urn are white.
